artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data-ingestion
  data_path: "artifacts/data-ingestion/credit_card.csv"
  data_table: "data_features"

dump_data:
  root_dir: artifacts/data
  input_train_path: "artifacts/data/X_train.pkl"
  input_test_path: "artifacts/data/X_test.pkl"
  input_valid_path: "artifacts/data/X_valid.pkl"
  output_train_path: "artifacts/data/y_train.pkl"
  output_test_path: "artifacts/data/y_test.pkl"
  output_valid_path: "artifacts/data/y_valid.pkl"

scale_data:
  root_dir: artifacts/preprocessing
  scaled_train_path: "artifacts/preprocessing/X_train.csv"
  scaled_test_path: "artifacts/preprocessing/X_test.csv"
  scaled_valid_path: "artifacts/preprocessing/X_valid.csv"
  scaler_model_path: "artifacts/models/scaler.pkl"

train_model:
  root_dir: "artifacts/models"
  model_path: "artifacts/models/model.pkl"

evaluation:
  root_dir: "artifacts/models"
  score_path: metrics/scores.json
  mlflow_dataset_path: "artifacts/data/ml_eval_result.csv"
  mlflow_exp_name: "ML Project"
  mlflow_run_name: "ml-eval"