artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data-ingestion
  data_path: "artifacts/data-ingestion/credit_card.csv"
  data_table: "data_features"

dump_data:
  root_dir: artifacts/data
  input_train_path: "artifacts/data/X_train.pkl"
  input_test_path: "artifacts/data/X_test.pkl"
  input_valid_path: "artifacts/data/X_valid.pkl"
  output_train_path: "artifacts/data/y_train.pkl"
  output_test_path: "artifacts/data/y_test.pkl"
  output_valid_path: "artifacts/data/y_valid.pkl"

scale_data:
  root_dir: artifacts/preprocessing
  scaled_train_path: "artifacts/preprocessing/X_train.csv"
  scaled_test_path: "artifacts/preprocessing/X_test.csv"
  scaled_valid_path: "artifacts/preprocessing/X_valid.csv"
  scaler_model_path: "artifacts/models/scaler.pkl"

train_model:
  root_dir: "artifacts/models"
  model_path: "artifacts/models/model.pkl"

evaluation:
  root_dir: "artifacts/models"
  train_score_path: metrics/train_scores.json
  test_score_path: metrics/test_scores.json
  valid_score_path: metrics/valid_scores.json
  mlflow_dataset_path: "artifacts/data/ml_eval_result.csv"
  mlflow_dataset_column:
    - 'V1'
    - 'V2'
    - 'V3'
    - 'V4'
    - 'V5'
    - 'V6'
    - 'V7'
    - 'V8'
    - 'V9'
    - 'V10'
    - 'V11'
    - 'V12'
    - 'V13'
    - 'V14'
    - 'V15'
    - 'V16'
    - 'V17'
    - 'V18'
    - 'V19'
    - 'V20'
    - 'V21'
    - 'V22'
    - 'V23'
    - 'V24'
    - 'V25'
    - 'V26'
    - 'V27'
    - 'V28'
    - 'Amount'
  mlflow_exp_name: "Credit Card Fraud Prediction"
  mlflow_run_name: "eval-hpo-lr"

predict:
  root_dir: "artifacts/predict"
  mlflow_model_name: "logistic_regression"
  mlflow_scaler_model_path: "scaler/scaler.pkl"